# Generated by Django 4.2 on 2023-04-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='date',
        ),
        migrations.AddField(
            model_name='livre',
            name='file',
            field=models.FileField(default='exit', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livre',
            name='nbPages',
            field=models.IntegerField(verbose_name='Nombre de Page'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='slug',
            field=models.SlugField(blank=True, default='djangodbmodelsfieldscharfield', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='titre',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
    ]
