# Generated by Django 4.1.7 on 2023-03-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membres", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_projet", models.CharField(max_length=150)),
                ("debut", models.DateField(blank=True)),
                ("deadline", models.DateField()),
                (
                    "etat_projet",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "En Cours"), (2, "Revue"), (3, "Terminé")],
                        default=1,
                    ),
                ),
                (
                    "admins",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="membres.membres",
                    ),
                ),
            ],
        ),
    ]
