# Generated by Django 4.1.7 on 2023-03-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membres", "0001_initial"),
        ("projets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=120)),
                (
                    "etat",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "En Cours"), (2, "Revue"), (3, "Terminé")],
                        default=1,
                    ),
                ),
                (
                    "membres",
                    models.ForeignKey(
                        default=django.db.models.deletion.SET_NULL,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="membres.membres",
                    ),
                ),
                (
                    "projets",
                    models.ForeignKey(
                        default=django.db.models.deletion.SET_NULL,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projets.projets",
                    ),
                ),
            ],
        ),
    ]
