# Generated by Django 4.1.7 on 2023-04-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taches",
            name="deadline",
            field=models.DateField(null=True),
        ),
    ]
