# Generated by Django 4.1.7 on 2023-03-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Membres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=120, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("mot_de_passe", models.CharField(max_length=10)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
            ],
        ),
    ]
